# Generated by Django 5.1.7 on 2025-06-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(default='')),
                ('actualfee', models.IntegerField(default='')),
                ('pendingfee', models.IntegerField(default='')),
                ('datetime', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
