# Generated by Django 5.1.7 on 2025-06-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='actualfee',
            new_name='Actualfee',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='datetime',
            new_name='Datetime',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='fee',
            new_name='Fee',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='pendingfee',
            new_name='Pendingfee',
        ),
    ]
