# Generated by Django 5.1.7 on 2025-06-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_fee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='Actualfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='Fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='Pendingfee',
            field=models.IntegerField(default=0),
        ),
    ]
