# Generated by Django 5.1.7 on 2025-06-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_fees_fes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fes',
            name='user',
        ),
        migrations.DeleteModel(
            name='fees',
        ),
        migrations.DeleteModel(
            name='fes',
        ),
    ]
