# Generated by Django 5.1.7 on 2025-07-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
